name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.4, '8.0', 8.1]
        eventsauce: ['^0.8.2']
        laravel: [8]
        code-gen: ['no']
        include:
          - php: 8.1
            laravel: 8
            code-gen: '^1.0'
            eventsauce: '^1.2.0'
          - php: 8.0
            laravel: 8
            code-gen: '^1.0'
            eventsauce: '^1.2.0'


    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install code-generation
        if: ${{ matrix.code-gen != 'no' }}
        run: |
          composer require "eventsauce/code-generation=${{ matrix.code-gen }}" -w --prefer-dist --no-interaction --no-update

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" -w --prefer-dist --no-interaction --no-update
          composer require "eventsauce/eventsauce=${{ matrix.eventsauce }}" -w --prefer-dist --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
